# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetRank1Tensor <- function(lambda, a, b, c) {
    .Call(`_tensorpca_GetRank1Tensor`, lambda, a, b, c)
}

TensorPCA <- function(X, tensor_rank, sigma, num_power_iter, use_unfolding_init=TRUE) {
    .Call(`_tensorpca_TensorPCA`, X, tensor_rank, sigma, num_power_iter, use_unfolding_init)
}

